### PR TITLE
Pass speed to inner resolvers

### LINKED ISSUE #982: Fix `--speed` for the resolver
The `--speed` option currently does nothing for the resolver, at least when combined with `--presenter` and not running against a CDS.

It is possible that it would work without `--presenter`, and this might be solved after #959 is fixed (?).

### PR DESCRIPTION
**Pull request by nickygerritsen**
Fixes #982

### CODE REVIEW

**Review by deboer-tim — APPROVED** [review]
Will fix the immediate problem, but:
- Why not directly pass in the resolveInfo now? Would be simpler code and if we (e.g.) provided a way to set initial scroll speed we wouldn't have to keep adding params.
- The issue now points out the fast/speed inconsistency too, so we should either fix that (the docs, not the code) or remove the 'fixes',

**Comment by nickygerritsen** [comment]
> Will fix the immediate problem, but:
> 
> * Why not directly pass in the resolveInfo now? Would be simpler code and if we (e.g.) provided a way to set initial scroll speed we wouldn't have to keep adding params.
> * The issue now points out the fast/speed inconsistency too, so we should either fix that (the docs, not the code) or remove the 'fixes',

Do you think nothing will break fi we pass the whole info? I can do that

**Comment by deboer-tim** [comment]
> > Will fix the immediate problem, but:
> > 
> > * Why not directly pass in the resolveInfo now? Would be simpler code and if we (e.g.) provided a way to set initial scroll speed we wouldn't have to keep adding params.
> > * The issue now points out the fast/speed inconsistency too, so we should either fix that (the docs, not the code) or remove the 'fixes',
> 
> Do you think nothing will break fi we pass the whole info? I can do that

Yes, that was the original intent - let the command line args customize one ResolveInfo and set it, instead of having multiple vars, passing them along, and then creating the ResolveInfo later on.

**Comment by nickygerritsen** [comment]
> > > Will fix the immediate problem, but:
> 
> > > 
> 
> > > * Why not directly pass in the resolveInfo now? Would be simpler code and if we (e.g.) provided a way to set initial scroll speed we wouldn't have to keep adding params.
> 
> > > * The issue now points out the fast/speed inconsistency too, so we should either fix that (the docs, not the code) or remove the 'fixes',
> 
> > 
> 
> > Do you think nothing will break fi we pass the whole info? I can do that
> 
> 
> 
> Yes, that was the original intent - let the command line args customize one ResolveInfo and set it, instead of having multiple vars, passing them along, and then creating the ResolveInfo later on.

Ok I will change this and test it

**Pull request merged**
