### PR TITLE
Determine base URL of API correctly.

### PR DESCRIPTION
**Pull request by nickygerritsen**
Instead of assuming the API of external CCS'es always starts with /api/, determine the real URL by using a regex on the CCS URL.
Kattis uses /clics-api/contests/xxxxx for a contest so it broke there if they use relative URL's.
Also use the root of the URL instead of the part before /api/ for absolute URL's, since I think that is what is meant in the spec.

@SuprDewd found this issue 😄.

### CODE REVIEW

**Comment by nickygerritsen** [comment]
Tested with a test Kattis contest for NWERC20 btw

**Review by deboer-tim — COMMENTED** [review]
Won't line 451 fail if the server is not on the default port #?

**Comment by nickygerritsen** [comment]
https://stackoverflow.com/questions/2142910/whats-the-difference-between-uri-host-and-uri-authority

> Authority = Host Name + Port No

I actually copied it from the decompiled `url.toExternalForm` code.

**Review by deboer-tim — APPROVED** [review]
Ah, I was mis-reading.

**Pull request merged**
